
package ru.stqa.pft.idsys.s.ru.id_sys.schemas.idbank.customer._2015._0;

import ru.stqa.pft.idsys.s.ru.roskazna.xsd.common.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IDBankCustomersPortType", targetNamespace = "http://www.id-sys.ru/schemas/idbank/customer/2015/0.01/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ru.id_sys.schemas.idbank.cik._2017._0.ObjectFactory.class,
    ObjectFactory.class,
    ru.stqa.pft.idsys.s.ru.roskazna.xsd.organization.ObjectFactory.class,
    ru.stqa.pft.idsys.s.com.triasoft.dev.schemas.eis.eregistry.pppr._2.ObjectFactory.class,
    ru.id_sys.schemas.idbank.common._2012._0.ObjectFactory.class,
    ru.id_sys.schemas.idbank.customer._2015._0.ObjectFactory.class,
    ru.cbr.dsig.v1.ObjectFactory.class,
    ru.cbr.ed.v2.ObjectFactory.class,
    ru.id_sys.schemas.idbank.esia._2015._0.ObjectFactory.class,
    ru.id_sys.schemas.idbank.notary._2014._1.ObjectFactory.class,
    ru.stqa.pft.idsys.s.ru.id_sys.schemas.idbank.thirdpartyorderservice._2015._0.ObjectFactory.class,
    ru.cbr.ed.leaftypes.v2.ObjectFactory.class
})
public interface IDBankCustomersPortType {


    /**
     * Запрос сведений о клиентах
     * 
     * @param request
     * @return
     *     returns ru.id_sys.schemas.idbank.customer._2015._0.LookupCustomersRs
     * @throws LookupCustomersErr
     */
    @WebMethod(operationName = "LookupCustomers", action = "http://www.id-sys.ru/schemas/idbank/customer/2015/0.01/LookupCustomers")
    @WebResult(name = "LookupCustomersRs", targetNamespace = "http://www.id-sys.ru/schemas/idbank/customer/2015/0.01/", partName = "response")
    public LookupCustomersRs lookupCustomers(
        @WebParam(name = "LookupCustomersRq", targetNamespace = "http://www.id-sys.ru/schemas/idbank/customer/2015/0.01/", partName = "request")
        LookupCustomersRq request)
        throws LookupCustomersErr
    ;

}
